local-simulation:
  user-workflow:
    workflow-name: "whitewall-credit-plaid"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../../secrets.yaml"
